### ISSUE TITLE
Translated texts are all question marks

### ISSUE THREAD

**Issue by vanbang9710** [EnergoStalin/subtitle-translate-mpv#2]
**To Reproduce**
1. Install as the readme instruction. crow can be called from the terminal.
2. play a video with MPV

**Expected behavior**
Translated text pops up.

**Screenshots**
![|50pct](https://i.imgur.com/MSrvHPq.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H2 (Build 19044.3086)

**Additional context**
Add any other context about the problem here. When running crow cli in powershell, it prints nothing ![|50pct](https://i.imgur.com/2Ksqqj1.png)

**Comment by EnergoStalin** [comment]
> Add any other context about the problem here. When running crow cli in powershell, it prints nothing

It's okay.

As i remember it's crow problem. Crow returns translation result in corresponding to language codepage as i know it's not possible to specify it return result in utf-8(what lua can operate). For me crow encodes output in [1251 codepage](https://github.com/EnergoStalin/subtitle-translate-mpv/blob/master/modules/translators/encodings/cp1251.lua) so i did the trick by [translating codepage](https://github.com/EnergoStalin/subtitle-translate-mpv/blob/5abd025c22e8348ff0a656ff8062714e6447c687/modules/translators/encodings/auto.lua#L10-L14) manually for my language.

I thinke'd of using iconv for that but unfortunately i cant bundle it with script cause it would lack multi platform support then.

I did a try to rewrite it in master-js branch but abandoned it for the sake of [miru](https://github.com/ThaUnknown/miru) and alternatives.

I shold've specified what it may not work just easy as expected tho. Sorry for confusion.

So that's i can suggest to resolve this:
1. Try to get crow use utf-8(perhaps more easier to just write support for another translator capable of setting output codepage into utf-8)
2. Determine what encoding it uses now and implement binding for this codepage in [auto.lua](https://github.com/EnergoStalin/subtitle-translate-mpv/blob/master/modules/translators/encodings/auto.lua#L10-L14)
3. Check Arial supports Vietnameese(unlikely but maybe)

I have this with same settings.
![image](https://github.com/EnergoStalin/subtitle-translate-mpv/assets/49844515/123effba-3247-4842-8b41-ed1c9eb12caa)
Crow also look at your regional settings as i figured out after reinstalling windows.
![image](https://github.com/EnergoStalin/subtitle-translate-mpv/assets/49844515/33344592-681a-4c60-af55-0ee8d01ba5d5)

**Comment by vanbang9710** [comment]
thank you for your detailed answer.
