### ISSUE TITLE
Macos

### ISSUE THREAD

**Issue by adriannedbailo** [EnergoStalin/subtitle-translate-mpv#4]
It works on mac?

**Comment by EnergoStalin** [comment]
I don't know but looks like [crow](https://github.com/crow-translate/crow-translate/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+macos) not works on mac well. So it wont work out of the box i guess. Can't test myself because i don't have mac and don't want spend time supporting it. You can easily implement support to different translator tho.

Let's say write modules/translators/own_translator.lua returning function which accepts from and to language arguments returning function accepting original line and returning translation. Then specify own_translator in config as translator and here you go. You can use [crow.lua](https://github.com/EnergoStalin/subtitle-translate-mpv/blob/master/modules/translators/crow.lua) for reference. Maybe you can find more suitable translator than crow because with crow such [problem](https://github.com/EnergoStalin/subtitle-translate-mpv/issues/2#issuecomment-1645473199) exists
